version: "3.8"

services:

  #nginx
  nginx:
    image: nginx:latest
    container_name: bt-nginx
    ports:
      - "8484:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www

  #app
  api:
    container_name: bt-app
    build:
      args:
        user: shaho
        uid: 1000
      context: .
      dockerfile: ./docker/Dockerfile
      network: host

#    env_file:
#      - .env
    volumes:
      - .:/var/www

  #mysql
  db:
    image: mysql:8.0
    container_name: bt-db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init/db:/docker-entrypoint-initdb.d
#          - /home/mysql_data:/var/lib/mysql
    ports:
      - "3309:3306"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}

  #phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: bt-phpmyadmin
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PMA_HOST: bt-db
      MYSQL_ROOT_PASSWORD:  ${DB_ROOT_PASSWORD}
    ports:
      - "8989:80"

volumes:
  mysql_data:
